#!/bin/sh -eu

#
# menu - pipe something to it, returns the chosen value in stdout
# requirements:
#   fzf or an alternative

in_pipe="$XDG_RUNTIME_DIR/menu-in.$$.pipe"
out_pipe="$XDG_RUNTIME_DIR/menu-out.$$.pipe"

mkfifo "$in_pipe" "$out_pipe"
trap "rm -f $in_pipe $out_pipe" EXIT

app_id=menu
chooser="fzf <$in_pipe >$out_pipe"

alacritty --class "$app_id" --command sh -c "$chooser" &

cat >"$in_pipe"
cat <"$out_pipe"
