#!/bin/sh

#
# wp - use a random wallpaper from a directory
# requirements:
#   hsetroot for x
#   swaybg for wayland

wp=$(ls ~/wp | shuf -n 1)

# just pass any argument for x
if [ $# -ne 0 ]; then
    hsetroot -fill ~/wp/$wp
else
    swaybg -i ~/wp/$wp --mode fill
fi
