#!/bin/sh

# wp - use a random wallpaper from a directory

wp=$(ls ~/etc/pic/wp/ | shuf -n 1)

# just pass any argument for x
if [ $# -ne 0 ]; then
  swaybg -i ~/etc/pic/wp/$1 --mode fill
else
  swaybg -i ~/etc/pic/wp/$wp --mode fill
fi
