#!/usr/bin/env bash

# infinite loop youtube downloader

music_dir="$HOME/torrent/music"

while :
do
    clear
    read -rp "url: " url
    cd $music_dir
    yt-dlp $url --add-metadata --embed-thumbnail --extract-audio --audio-format mp3 --restrict-filenames
done
