#!/usr/bin/env bash

# downlaod videos from yt with my preferred settings
# deps: yt-dlp, ffmpeg

read -rp "url: " url
yt-dlp -f 'bestvideo[height<=720]+bestaudio/best[height<=720]' \
  --write-auto-sub --sub-lang=en --embed-subs \
  --merge-output-format mp4 $url
